ryran/xsos

README.md
The relative path wasn't rendered correctly by Markdown. Replaced it
with direct link.
=> README: fix broken url

xsos, xsos-bash-completion.bash
The ps module now takes threading into account via the `ps auxm` command (localhost) or the `sos_commands/process/ps_auxwwm` file (sosreport).
When running with `--threads`, the info displayed in the sleep, zombie, top cpu procs, & top mem procs sections shows threads instead of processes.
```
$ xsos -p -v0
PS CHECK
Total number of threads/processes: 
1190 / 311
Top users of CPU & MEM: 
USER  %CPU   %MEM   RSS 
rsaw  10.0%  47.0%  3.74 GiB
gdm   0.1%   3.4%   0.33 GiB
root  0.0%   3.1%   0.33 GiB
Uninteruptible sleep threads/processes (0/0): 
[None]
Defunct zombie threads/processes (1/1): 
USER     PID    %CPU  %MEM  VSZ-MiB  RSS-MiB  TTY    STAT  START  TIME    COMMAND 
polkitd  2437   0.0   0.0   0        0        ?      Z     Jun19  0:00    [pkla-check-auth] 
Top CPU-using processes: …
```
=> v0.5.23: implement thread-parsing with ps auxm, thanks to #146

README.md
Update function was removed in 6c7c767 so I'm removing it from README.
Still needs to be removed from bash completion, but I'm not familiar with bash completion so I can't test it.
=> remove update function references from README

xsos
- Remove `--scrub-ip`
- Remove `--scrub-mac`
- Add `XSOS_SCRUB_SERIAL` env variable (to the already-existing `XSOS_SCRUB_IP_HN` and `XSOS_SCRUB_MACADDR`)
- Add `--scrub` option that does all 3
- If you want finer control, you can use variables
=> v0.7.0: #168 replaced scrub opts w/ --scrub; scrub dmidecode

xsos
This fixes #203 and #205.
If you can't see the screenshot, here's some sample Memory output from the version of `xsos -b` prior to this commit:
```
Memory:
2048 MB (2 GB) total
64 of 96 DIMMs populated (system max capacity 1536 GB)
```
With the fixes + enhancements from this commit, the output for the same system is now:
```
Memory:
Total: 2097152 MiB (2048 GiB)
DIMMs: 64 of 96 populated
MaxCapacity: 6291456 MiB (6144 GiB / 6.00 TiB)
```
=> v0.7.10: fix for dmidecode-parsing issues #203 and #205

xsos
People often see the "increase this" message and go off on tangents
making these values far too large when there are other things to be
considered. In a way I wish we'd never put these in xsos, but they are a
handy prompt to look into other areas of softirq performance some more.
Soften the warning to "consider reviewing" this tunable, rather than
alert the user that the tunables are too small, which they probably
aren't. I've also modified the linked knowledgebase solution to advise
considering a more holistic performance tuning view.
Signed-off-by: Jamie Bainbridge jamie.bainbridge@gmail.com
=> softirq: Soften budget/backlog tuning suggestion

xsos
8139too logs its ring buffer loss as "rx_lost_in_ring"
=> Add "lost" to packet loss grep

xsos
An internal Olson timezone is used for some commands. Extend the
capturing of the timezone to run on EL5/EL6/EL7 sosreports and live, and
print the timezone.
=> os: Add tz database (aka Olson) style timezone

xsos
Upstream sos now collects df_-al_-x_autofs instead of df_-al. The file
can be parsed the same way, so just check for the namechange.
Resolves https://github.com/ryran/xsos/issues/229
=> kdump: df_-al namechange

xsos
Upstream lspci now adds a "domain" to PCI device names, like so:
Ethernet controller: Old line
Ethernet controller [0800]: New line
Optionally check for this when building the lspci list of devices.
Also print the full device line including PCI ID and rev.
=> [lspci] Support domain format, add PCI ID

xsos
vm.min_free_kbytes is popularily used for vm tunings.
vm.vfs_cache_pressure is also pupularily used for caching of
directory and inode objects.
=> sysctl: Add vm.min_free_kbytes and vm.vfs_cache_pressure

xsos
Dark Grey is actually Black, which is not possible to read on dark
terminal backgrounds. Replace with light grey where appropriate.
=> xsos: Remove Dark Grey and Black text

xsos
Some ethtool counters match "false positives" such as Intel's fdir_miss
or Virtual Ethernet Bridge veb.dropped which we don't want to see.
The normal way to do this is a negative lookahead/lookbehind but grep
and awk's ERE don't support those. Convert the existing ethtool regex to
an awk-syntax match and use awk logic to exclude unwanted strings.
=> ethtool: add exclusions

xsos, xsos-bash-completion.bash
Fixes #138 .
First stab at adding support for teaming. Tested with a few activebackup and
lacp runner teams.
Problems:
- Like the bonding xsos module, this teaming module output gets ugly really
quickly as the length of the TEAM_CONFIG string goes up.
- None of the output from a standard sosreport provides the original MAC of a
team port.
Signed-off-by: Patrick Talbert <ptalbert@redhat.com>
=> Add teaming support

xsos
Fixes #235 .
Modern distros may not have the brctl command available, instead using the
'bridge' command from the iproute suite. It is expected that sos will be updated
to accomodate this change so prepare for it here.
Signed-off-by: Patrick Talbert <ptalbert@redhat.com>
=> Update ip output to support 'bridge' command output

xsos
EL8 includes "minmtu" and "maxmtu" which cause additonal printing on the
address lines. Change the grep to include the leading space, matching
only on the actual MTU value.
=> ipaddr: fix address output on EL8

xsos
THP can still be enabled without the system having allocated any
anonymous huge pages. Change text to reflect THP "usage" rather than
being turned off.
It would be nice to have proper display of enabled/disabled/madvise in
future, as described in: https://github.com/ryran/xsos/issues/254
Reported-by: karlabbott on GitHub
=> meminfo: Accurately describe THP usage

xsos
Adds support for the following:
* `ss_-peaonmi`: Provides an overview of current network connections having some predefined fields > 0. Useful for checking sessions with drops, retrans, etc
* Activated via `-S`, `--ss`
* File can be specified via --S (defaults to `sos_commands/networking/ss_-peaonmi`)
* What fields to check can be overriden via `XSOS_SS_CHECK_FIELDS` environment variable
* Added to `--net` or `--all`
* `Firewall`: Provides an overview of current firewall service status status and number of rules loaded by either `iptables` or `nftables`
* Requires having `sos_commands/systemd/systemctl_status_--all`
* Activated via `-F`, `--firewall`
* Detects whether any of `{iptables,nftables,firewalld}` services are enabled/running
* Added to `--net` or `--all`
* `ifcfg-*`: Provides an …
=> New modules SSCHECK() FIREWALL() IFCFG()

xsos
As discussed on https://access.redhat.com/discussions/469323 there are
some cases where symlinks may fail after copying a sosreport, or maybe
because of a partial sos collection.
Catch a couple of these cases by also looking for the true path of the
files in question.
Reported-by: Bill Marshall <BMARSH@US.IBM.COM>
=> Catch some conditions where symlinks fail

xsos
lsblk provides a nice tree-based representation of disk layout.
df provides a nice view of filesystem layout.
Add them to the STORAGE section.
Use base "lsblk" for most coverage of sos versions and most useful
output compared to other command options like "-D" or "-t".
Use "df -al -x autofs" like sosreport does.
Add a nice bright header to first line of each.
Based on https://github.com/ryran/xsos/pull/243
Contributed-by: Chris Ruettimann <chris@bitbull.ch>
=> Add lsblk and df output to STORAGE

xsos
Rule counts were being ignored when no firewall services were enabled. 
This changes this behavior so rule count is always printed when there are iptables or nftables rules loaded.
=> FIREWALL() print rule count even when no firewall services are enabled

xsos
Current versions of `grep` warn that `egrep` is being deprecated in favor of `grep -E`.
=> replace egrep with grep -E

xsos
Looks like an oversight when the -p/--ps option was added originally, but without this there's no output from "xsos -p" (live).
=> Allow -p/--ps option in the live local mode as well

xsos
Fix gawk crash when using `printf` to print column names that contain a `%` from the ps output
This seems to come from this change in gawk 5.3.1
8. The implementation of printf/sprintf has been thoroughly reworked
in order to make the code more maintainable and to fix a goodly
number of corner cases.
Looks like printf was interpreting "%CPU" or "%MEM" as a format spec and expecting an argument to be provided, otherwise it crashes with the following error:
gawk: cmd. line:32: (FILENAME=- FNR=1) fatal: not enough arguments to satisfy format string
Fixes #285
=> Fix gawk crash in ps output
