xsos
In the OS module, i.e., the default module when run with no options:
- `/etc/sysconfig/rhn/up2date` is now parsed for proxy info
* always shows `enableProxy =` but only shows more if that's set to `1` and uses sane logic to decide which additional things to show (e.g., if `httpProxy` is unset, there's no point in checking/showing `enableProxyAuth` and if `enableProxyAuth` is unset, there's no point in checking/showing `proxyUser` and `proxyPassword`)
- `/etc/rhsm/rhsm.conf` is now parsed for RHSM funness (including proxy stuff)
* always shows `rhsm_hostname` and `proxy_hostname` but only shows more if the latter is set
- `/etc/yum/pluginconf.d/` is now parsed to display a list of enabled yum plugins
Examples:
```
[rsaw@f21 ~]$ xsos | head
OS
Hostname: f21
Distro:   [redhat-release] Fedora …
```
=> add RHSM & info about yum plugins to os module

xsos, xsos-bash-completion.bash
=> add new -f/--F/--intrupt options to parse /proc/interrupts data into a binary graph

xsos
=> v0.5.16: make kdump svc-enablement status w/systemd more clear #129

xsos
=> v0.5.17: make memgraph (--mem) characters simpler & more legible

xsos
=> Update taint check

xsos
=> a few random whitespace fixes

xsos
=> Moar 442 sysctls

CHANGELOG.md, xsos, xsos-bash-completion.bash
- Fixed issue where `--mpath` option wouldn't work on localhost
- Removed `-U` & `--update` from bash tab-completion
- Cleaned up ENV variable declarations
- Removed an extra debug line in the new thread code that was creating `/tmp/thread.debug`
=> fix a few tiny bugs, nix -U/--update from tabcomplete + random cleanup

xsos
=> add kernel.sysrq to kdump #167

xsos
Completely overhaul the logic in the disks-function. Add tons of block-types. Fix plenty of problems.
=> v0.7.5: big overhaul of /proc/partitions parser #180

xsos
=> add support in OS module for finding UEFI GRUB/GRUB2 cfgfile

xsos
=> v0.7.9: update --scrub to wipe out proxy info in os module #185

xsos
=> Lathan better threads

xsos
=> Send brctl show errors to devnull

xsos
Simplified hung_task_warnings a bit from 11cf0bddadb85f42886c51ff0dc5840c8b7aa9ee
=> sysctl: add hung_task_warnings, max_map_count, zone_reclaim_mode

xsos
THP usage is added in memory section
=>     meminfo: Add THP usage

xsos
=> meminfo: Amending THP usage and description

xsos
=> sysctl: add vm.force_cgroup_v2_swappiness

xsos
=> sysctl: add fs.dentry-state

xsos
=> sysctl: fix with printf for the value 2 of vm.overcommit_memory

xsos
=> meminfo: Adding Percpu usage

xsos
In-use memory is calculated as (Total − Free − Rsvd).
Entire Usage is condensed into a single line.
=> meminfo: Amending Hugepages usage
